# Generated by Django 3.1 on 2020-08-27 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NW', 'New'), ('IP', 'In Progress'), ('DN', 'Done'), ('IN', 'Invalid')], default='NW', max_length=2)),
                ('assigned', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('completed', models.CharField(blank=True, max_length=50, null=True)),
                ('filing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
